name: Generate GitHub Streaks

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install & Build streaks-action
        run: |
          cd .github/streaks-action
          npm install
          npm run build

      - name: Run streak generator
        run: |
          cd .github/streaks-action
          node dist/index.js \
            --username ${{ github.actor }} \
            --output ../../streaks.svg

      - name: Commit and push SVG
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "chore: update streaks.svg"
          file_pattern: streaks.svg
