name: Generate GitHub Streaks

on:
  push:
    paths:
      - scripts/streaks/**
      - .github/workflows/streaks.yml
      - assets/**
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  generate-streaks:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.STREAKS_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Generate streaks
        run: |
          echo "🔧 Running streak generator..."
          npx ts-node scripts/streaks/index.ts

      - name: Show SVG preview (first 10 lines)
        run: head -n 10 assets/streaks.svg || echo "streaks.svg not found"

      - name: Commit streaks.svg if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          if git diff --quiet assets/streaks.svg; then
            echo "No changes detected in streaks.svg"
          else
            echo "Changes detected, committing streaks.svg..."
            git add assets/streaks.svg
            git commit -m "Update GitHub streaks"
            git push
