# .github/workflows/streaks.yml

name: Generate GitHub Streaks

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'assets/**'

  schedule:
    - cron: '30 18 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      STREAKS_TOKEN: ${{ secrets.STREAKS_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Generate streaks SVG
        run: npm run generate-streaks

      - name: Commit & push updated SVG
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: chore: update generated streaks SVG
          file_pattern: assets/streaks.svg
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          push: true
